#  // ======================================================================================= \\
# ||                                                                                           ||
# ||                                                                                           ||
# ||       _____    ____    _   _   ______   _____    _____      __     __  __  __   _         ||
# ||     / ____|  / __ \  | \ | | |  ____| |_   _|  / ____|     \ \   / / |  \/  | | |         ||
# ||    | |      | |  | | |  \| | | |__      | |   | |  __       \ \_/ /  | \  / | | |         ||
# ||    | |      | |  | | | . ` | |  __|     | |   | | |_ |       \   /   | |\/| | | |         ||
# ||    | |____  | |__| | | |\  | | |       _| |_  | |__| |  _     | |    | |  | | | |____     ||
# ||     \_____|  \____/  |_| \_| |_|      |_____|  \_____| (_)    |_|    |_|  |_| |______|    ||
# ||                                                                                           ||
# ||                                                                                           ||
# \\ ======================================================================================== //

#
# INTRODUCTION:
# This file contains all the settings for the plugin. You can change the settings to your liking.


#      _           _             _
#     | |         | |           | |
#   __| |   __ _  | |_    __ _  | |__     __ _   ___    ___
#  / _` |  / _` | | __|  / _` | | '_ \   / _` | / __|  / _ \
# | (_| | | (_| | | |_  | (_| | | |_) | | (_| | \__ \ |  __/
#  \__,_|  \__,_|  \__|  \__,_| |_.__/   \__,_| |___/  \___|

# Enter the credentials for your MySQL database here, and restart the server to apply the changes.
host: '127.0.0.1'
port: 3306
database: 'minecraft'
username: 'root'
password: '0GlPo[)(eJU7sOk}UTza'

#   _                             _
# | |                           | |
# | |_    ___     __ _    __ _  | |   ___
# | __|  / _ \   / _` |  / _` | | |  / _ \
# | |_  | (_) | | (_| | | (_| | | | |  __/
#  \__|  \___/   \__, |  \__, | |_|  \___|
#                 __/ |   __/ |
#                |___/   |___/
#                                                             _
#                                                            | |
#   ___    ___    _ __ ___    _ __ ___     __ _   _ __     __| |  ___
#  / __|  / _ \  | '_ ` _ \  | '_ ` _ \   / _` | | '_ \   / _` | / __|
# | (__  | (_) | | | | | | | | | | | | | | (_| | | | | | | (_| | \__ \
#  \___|  \___/  |_| |_| |_| |_| |_| |_|  \__,_| |_| |_|  \__,_| |___/

# Toggle the commands on or off by setting the value of the specific command to true or false.
command.help.noArgs.enabled: true
command.help.reload.enabled: true
command.help.database.enabled: true
command.reload.noArgs.enabled: true
command.reload.config.enabled: true
command.database.checkConnection.enabled: true
command.database.noArgs.enabled: true

command:
  help:
    main:
      permission: 'friendships.help'
      description: 'Shows all the commands'
      syntax: '/friendships help'
      aliases:
        - 'help'
        - 'helpme'
    database:
      permission: 'friendships.help.database'
      description: 'Shows all database commands'
      syntax: '/friendships help database'
      aliases:
        - 'database'
        - 'db'
    reload:
      permission: 'friendships.help.reload'
      description: 'Shows all reload commands'
      syntax: '/friendships help reload'
      aliases:
        - 'reload'
        - 'rl'
  reload:
    main:
      permission: 'friendships.reload'
      description: 'Reloads the selected file(s)'
      syntax: '/friendships reload'
      aliases:
        - 'reload'
        - 'rl'
    config:
      permission: 'friendships.reload.config'
      description: 'Reloads the config.yml file'
      syntax: '/friendships reload config'
      aliases:
        - 'config'
        - 'cfg'
  database:
    main:
      permission: 'friendships.database'
      description: 'Perform database operations'
      syntax: '/friendships database'
      aliases:
        - 'database'
        - 'db'
    checkConnection:
      permission: 'friendships.database.checkconnection'
      description: 'Check on the database connection'
      syntax: '/friendships database checkconnection'
      aliases:
        - 'checkconnection'
        - 'checkconn'